# Generated by Django 3.1.3 on 2021-05-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='software_developer',
            field=models.BooleanField(default=False),
        ),
    ]
