# Generated by Django 3.1.3 on 2021-05-24 15:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210524_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
