# Generated by Django 3.1.3 on 2021-05-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210524_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
