# Generated by Django 3.1.3 on 2021-05-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_users_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='software_developer',
        ),
    ]
